simplemooc/courses/urls.py
from django.urls import path, re_path
from . import views

app_name='courses'

urlpatterns = [
    path('', views.index, name='index'),
    # re_path('(?P<pk>\d+)/', views.details, name='details'),
    re_path('(?P<slug>[\w_-]+)/inscricao/', views.enrollment, name='enrollment'),
    re_path('(?P<slug>[\w_-]+)/anuncios/', views.announcements, name='announcements'),
    re_path('(?P<slug>[\w_-]+)/', views.details, name='details'),

]

simplemooc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('simplemooc.core.urls', namespace='core')),
    path('conta/', include('simplemooc.accounts.urls', namespace='account')),
    path('cursos/', include('simplemooc.courses.urls', namespace='courses')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

simplemooc/courses/models.py
from django.db import models
from django.conf import settings

class CourseManager(models.Manager):
	
	def search(self, query):
		return self.get_queryset().filter(
			models.Q(name__icontains = query) |
			models.Q(description__icontains = query)
		)


class Course(models.Model):
	name = models.CharField('Nome', max_length=100)
	slug = models.SlugField('Atalho')
	description = models.TextField('Descrição Simples', blank=True)
	about = models.TextField('Sobre o Curso', blank=True)
	start_date = models.DateField('Data de Início', null=True, blank=True)
	image = models.ImageField(upload_to='courses/images', verbose_name='Imagem', null=True, blank=True)
	created_at = models.DateTimeField('Criado em', auto_now_add=True)
	updated_at = models.DateTimeField('Atualizado em', auto_now=True)

	objects = CourseManager()

	def __str__(self):
		return self.name

	@models.permalink
	def get_absolute_url(self):
		return ('courses:details', (), {'slug': self.slug})

	class Meta:
		verbose_name = 'Curso'
		verbose_name_plural = 'Cursos'
		ordering = ['name']

class Enrollment(models.Model):
	"""docstring for Enrollment"""
	STATUS_CHOICES = (
		(0, 'Pendente'),
		(1, 'Aprovado'),
		(2, 'Cancelado'),
	)

	user = models.ForeignKey(
		settings.AUTH_USER_MODEL,
		verbose_name='Usuário',
		related_name='enrollments',
		on_delete=models.DO_NOTHING
	)
	
	course = models.ForeignKey(
		Course,
		verbose_name='Curso',
		related_name='enrollments',
		on_delete=models.DO_NOTHING
	)

	status = models.IntegerField('Situação', choices=STATUS_CHOICES, default=1, blank=True)

	created_at = models.DateTimeField('Criado em', auto_now_add=True)
	updated_at = models.DateTimeField('Atualizado em', auto_now=True)

	class Meta:
		verbose_name = 'Inscrição'
		verbose_name_plural = 'Inscrições'
		unique_together = (
			('user', 'course'),
		)

	def active(self):
		self.status = 1
		self.save()

	def is_approved(self):
		return self.status == 1

simplemooc/courses/forms.py
from django import forms
from django.core.mail import send_mail
from django.conf import settings

from simplemooc.core.mail import send_mail_template


class ContactCourse(forms.Form):
	name = forms.CharField(label='Nome', max_length=100)
	email = forms.EmailField(label='E-mail')
	message = forms.CharField(label='Mensagem/Dúvida', widget=forms.Textarea)

	def send_mail(self, course):
		subject = '[%s] Contato' % course
		template_name = 'courses/contact_email.html'
		context = {
			'name': self.cleaned_data['name'],
			'email': self.cleaned_data['email'],
			'message': self.cleaned_data['message'],
		}

		send_mail_template(
			subject, 
			template_name,
			context,
			[settings.CONTACT_EMAIL]
		)

simplemooc/courses/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.conf import settings

from .models import Course, Enrollment
from .forms import ContactCourse

def index(request):
	courses = Course.objects.all()
	template_name = 'courses/index.html'
	#variáveis
	context = {
		'courses': courses
	}

	return render(request, template_name, context)

def details(request, slug):
	# course = get_object_or_404(Course, pk=pk)
	course = get_object_or_404(Course, slug=slug)
	context = {}

	if request.method == 'POST':
		form = ContactCourse(request.POST)
		if form.is_valid():
			context['is_valid'] = True
			form.send_mail(course)
			# print(form.cleaned_data['name'])
			# print(form.cleaned_data['message'])
			form = ContactCourse()

	else:
		form = ContactCourse()

	context['form'] = form
	context['course'] = course

	template_name = 'courses/details.html'
	return render(request, template_name, context)

@login_required
def enrollment(request, slug):
	course = get_object_or_404(Course, slug=slug)
	enrollment, created = Enrollment.objects.get_or_create(user=request.user, course=course)
	if created:
		# enrollment.active()
		flash = 'Você foi inscrito no curso com sucesso!'
		messages.success(request, flash)
	else:
		flash = 'Você já está inscrito neste curso.'
		messages.info(request, flash)
	return redirect('accounts:dashboard')

@login_required
def announcements(request, slug):
	course = get_object_or_404(Course, slug=slug)
	if not request.user.is_staff:
		enrollment = get_object_or_404(Enrollment, user=request.user, course=course)
		if not enrollment.is_approved():
			messages.error(request, 'A sua inscrição está pendente.')
			return redirect('accounts:dashboard')

	template_name = 'courses/announcements.html'
	context = {
		'course': course
	}
	return render(request, template_name, context)

simplemooc/courses/templates/courses/announcements.html
{% extends "accounts/dashboard.html" %}

{% block menu_options %}
    <li class="pure-menu-heading">
        {{ course }}
    </li>
    <li>
        <a href="#">
            <i class="fa fa-video-camera"></i>
            Aulas e Materiais
        </a>
    </li>
    <li>
        <a href="#">
            <i class="fa fa-info-circle"></i>
            Informações
        </a>
    </li>
    <li>
        <a href="#">
            <i class="fa fa-envelope"></i>
            Anúncios
        </a>
    </li>
    <li>
        <a href="#">
            <i class="fa fa-comments"></i>
            Fórum de Dúvidas
        </a>
    </li>

    <!-- chama o conteúdo base do bloco -->
    {{ block.super }}
{% endblock %}

{% block dashboard_content %}
    <div class="well">
        <h2>Iníco das aulas, sejam bem vindos</h2>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
            cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
            proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </p>
        <p>
            <a href="#comments" title="">
            <i class="fa fa-comments-o"></i>
            10 Comentários
            </a>
        </p>
    </div>
    <div class="well">
        <h2>Iníco das aulas, sejam bem vindos</h2>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
            cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
            proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </p>
        <p>
            <a href="#comments" title="">
            <i class="fa fa-comments-o"></i>
            10 Comentários
            </a>
        </p>
    </div>
</div>	
{% endblock %}

simplemooc/courses/templates/courses/contact_email.html
<p><strong>Nome</strong>: {{ name }}</p>
<p><strong>E-mail</strong>: {{ email }}</p>

{{ message|linebreaks }}

simplemooc/courses/templates/courses/details.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <div class="splash">
        <div class="pure-g-r">
            <div class="pure-u-1">
                <div class="l-box splash-text">
                    <h1 class="splash-head">
                        {{ course }}
                    </h1>
                    
                    <h2 class="splash-subhead">
                        {{ course.description }}
                    </h2>
                    
                    <p>
                        <a href="{% url 'courses:enrollment' course.slug %}" class="pure-button primary-button">Inscreva-se</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-2-3">
            <div class="l-box">
                <h4 class="content-subhead">Sobre o Curso</h4>
                {{ course.about|linebreaks }}
            </div>
        </div>
        <div class="pure-u-1-3">
            <div class="l-box">
                {% if course.image %}
                    <img src="{{ course.image.url }}" alt="" />
                {% else %}
                    <img src="{% static 'img/course-image.png' %}" alt="" />
                {% endif %}
            </div>
        </div>
    </div>

    <div class="pure-g-r content-ribbon">
        <div class="pure-u-2-3">
            <div class="l-box">
                <h4 class="content-subhead">Sobre o Curso</h4>
                {{ course.about|linebreaks }}
            </div>
        </div>
        <div class="pure-u-1-3">
            <div class="l-box">
                {% if course.image %}
                    <img src="{{ course.image.url }}" alt="" />
                {% else %}
                    <img src="{% static 'img/course-image.png' %}" alt="" />
                {% endif %}
                
                <h4>Dúvidas?</h4>
                <p>
                    <a href="#contato" title="" class="pure-button">Fale Conosco</a>
                </p>
            </div>
        </div>
    </div>

    <div action='#contato' class="pure-g-r content-ribbon" id="contato">
        <div class="pure-u-1">
            <h3>Tire sua dúvida sobre o Curso</h3>

            {% if is_valid %}
                <p> Você enviou o formulário com sucesso! :) </p>
            {% endif %}

            <form class="pure-form pure-form-aligned" method="post">
                {% csrf_token %}
                <fieldset>
                    {% for field in form %}
                        <div class="pure-control-group">
                            {{ field.label_tag }}
                            {{ field }}
                            {{ field.errors }}
<!--                             {% if field.errors %}
                                <ul class="errorlist">
                                    {% for error in field.errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %} -->
                        </div>
                    {% endfor %}
                    <div class="pure-controls">
                        <button type="submit" class="pure-button pure-button-primary">Enviar</button>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
{% endblock %}

simplemooc/courses/templates/courses/index.html
{% extends "base.html" %}

{% load static %}

{% block content %}
	<div class="pure-g-r content-ribbon">
	    <div class="pure-u-1">
	        <div class="l-box">
	            <h4 class="content-subhead">Listagem de Cursos do SimpleMOOC</h4>
	            <p>Abaixo a lista de cursos disponíveis na plataforma</p>
	        </div>
	    </div>
	</div>
	
	{% for course in courses %}
		<div class="pure-g-r content-ribbon">
		    <div class="pure-u-1-3">
		        <div class="l-box">
		            <a href="{{ course.get_absolute_url }}">
			            {% if course.image %}
				            <img src="{{ course.image.url }}" alt="{{ course.name }}" />
			            {% else %}
				            <img src="{% static 'img/course-image.png' %}" alt="{{ course.name }}" />
			            {% endif %}
		            </a>
		        </div>
		    </div>

		    <div class="pure-u-2-3">
		        <div class="l-box">
		            <h4 class="content-subhead">
		            	<a href="{{ course.get_absolute_url }}" title="">{{ course.name }}</a>
		            </h4>
		            
		            {{ course.description|linebreaks }}
		        </div>
		    </div>
		</div>

		{% empty %} <!-- Se no `for` for vazio, executa abaixo -->
		
		<div class="pure-g-r content-ribbon">
		    <div class="pure-u-1">
		        <div class="l-box">
		            <p>Nenhum curso está disponível na plataforma</p>
		        </div>
		    </div>
		</div>
	{% endfor %}
{% endblock %}