simplemooc/accounts/urls.py
from django.urls import path, re_path, include
from django.contrib.auth.views import login, logout
from . import views

app_name='accounts'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('entrar/', login, {'template_name': 'accounts/login.html'}, name='login'),
    path('sair/', logout, {'next_page': 'core:home'}, name='logout'),
    path('cadastro/', views.register, name='register'),
    path('renovar-senha/', views.password_reset, name='password_reset'),
    re_path('confirmar-nova-senha/(?P<key>\w+)/', views.password_reset_confirm, name='password_reset_confirm'),
    path('editar/', views.edit, name='edit'),
    path('editar-senha/', views.edit_password, name='edit_password'),
]

simplemooc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('simplemooc.core.urls', namespace='core')),
    path('conta/', include('simplemooc.accounts.urls', namespace='account')),
    path('cursos/', include('simplemooc.courses.urls', namespace='courses')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

simplemooc/accounts/models.py
import re
from django.db import models
from django.core import validators
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.conf import settings

# Create your models here.

class User(AbstractBaseUser, PermissionsMixin):
	"""docstring for User"""
	
	invalid_username = 'O nome de usuário só poder conter letras, dígitos ou @/./+/-/_'
	username = models.CharField(
		'Nome do Usuário', 
		max_length=30, 
		unique=True,
		validators=[validators.RegexValidator(re.compile('^[\w.@+-]+$'), invalid_username, 'invalid')]
	)
	email = models.EmailField('E-mail', unique=True)
	name = models.CharField('Nome', max_length=100, blank=True)
	is_active = models.BooleanField('Está ativo?', blank=True, default=True)
	is_staff = models.BooleanField('Administrador?', blank=True, default=False)
	date_joined = models.DateTimeField('Data de Cadastro', auto_now_add=True)

	objects = UserManager()

	USERNAME_FIELD = 'username' # Único e será usado como username
	REQUIRED_FIELDS = ['email']

	def __str__(self):
		return self.name or self.username # Se houver nome, se não username		

	def get_short_name(self):
		return self.username

	def get_full_name(self):
		return str(self)

	class Meta:
		verbose_name = 'Usuário'
		verbose_name_plural = 'Usuários'

class PasswordReset(models.Model):
	"""docstring for PasswordReset"""
	user = models.ForeignKey(
		settings.AUTH_USER_MODEL, 
		verbose_name='Usuário',
		on_delete=models.DO_NOTHING,
		related_name='resets'
	)

	key = models.CharField('Chave', max_length=100, unique=True)
	created_at = models.DateTimeField('Criado em', auto_now_add=True)
	cofirmed = models.BooleanField('Confirmado?', default=False, blank=True)

	def __str__(self):
		return '{0} em {1}'.format(self.user, self.created_at)

	class Meta:
		verbose_name = 'Nova Senha'
		verbose_name_plural = 'Novas Senhas'
		ordering = ['-created_at']

simplemooc/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

from simplemooc.core.mail import send_mail_template
from simplemooc.core.utils import generate_hash_key

from .models import PasswordReset

User = get_user_model()

class PasswordResetForm(forms.Form):
	"""docstring for PasswordResetForm"""
	email = forms.EmailField(label='E-mail')

	def clean_email(self):
		email = self.cleaned_data['email']
		if User.objects.filter(email=email).exists():
			return email
			
		raise forms.ValidationError('Nenhum usuário encontrado com este e-mail')

	def save(self):
		user = User.objects.get(email=self.cleaned_data['email'])
		key = generate_hash_key(user.username)
		reset = PasswordReset(key=key, user=user)
		reset.save()

		template_name = 'accounts/password_reset_mail.html'
		subject = 'Criar nova senha no Simple MOOC'
		context = {
			'reset': reset,
		}
		send_mail_template(subject, template_name, context, [user.email])


class RegisterForm(forms.ModelForm):
	
	password1 = forms.CharField(label='Senha', widget=forms.PasswordInput)
	password2 = forms.CharField(label='Confirmação de senha', widget=forms.PasswordInput)

	def clean_password2(self):
		password1 = self.cleaned_data.get("password1")
		password2 = self.cleaned_data.get("password2")
		if password1 and password2 and password1 != password2:
			raise forms.ValidationError('A confirmação de senha não está correta')
		return password2

	def save(self, commit=True):
		user = super(RegisterForm, self).save(commit=False)
		user.set_password(self.cleaned_data['password1'])
		if commit:
			user.save()

		return user

	class Meta:
		model = User
		fields = ['username', 'email']

class EditAccountForm(forms.ModelForm):

	class Meta:
		model = User
		fields = ['username', 'email', 'name']	

simplemooc/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm, SetPasswordForm
from django.conf import settings
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from simplemooc.core.utils import generate_hash_key
from simplemooc.courses.models import Enrollment

from .forms import RegisterForm, EditAccountForm, PasswordResetForm
from .models import PasswordReset
# Create your views here.

User = get_user_model()

@login_required
def dashboard(request):
	template_name = 'accounts/dashboard.html'
	context = {}
	context['enrollments'] = Enrollment.objects.filter(user=request.user)
	return render(request, template_name, context)

@login_required
def edit(request):
	template_name = 'accounts/edit.html'
	context = {}

	if request.method == 'POST':
		form = EditAccountForm(request.POST, instance = request.user)
		if form.is_valid():
			form.save()
			flash = 'Os dados da sua conta foram atualizados com sucesso!'
			messages.success(request, flash)
			return redirect('accounts:dashboard')
	else:
		form = EditAccountForm(instance = request.user)

	context['form'] = form
	return render(request, template_name, context)

@login_required
def edit_password(request):
	template_name = 'accounts/edit_password.html'
	context = {}
	if request.method == 'POST':
		form = PasswordChangeForm(data=request.POST, user=request.user)
		if form.is_valid():
			form.save()
			context['success'] = True
	else:
		form = PasswordChangeForm(user=request.user)

	context['form'] = form
	return render(request, template_name, context)

def register(request):
	template_name = 'accounts/register.html'

	if request.method == 'POST':
		form = RegisterForm(request.POST)
		if form.is_valid():
			user = form.save()
			user = authenticate(username=user.username, password=form.cleaned_data['password1'])
			login(request, user)
			return redirect('core:home')
	else:
		form = RegisterForm
	
	context = {
		'form': form
	}

	return render(request, template_name, context)

def password_reset(request):
	template_name = 'accounts/password_reset.html'
	form = PasswordResetForm(request.POST or None)
	context = {}	
	if form.is_valid():
		form.save()
		context['success'] = True
	context['form'] = form
	return render(request, template_name, context)

def password_reset_confirm(request, key):
	template_name = 'accounts/password_reset_confirm.html'
	context = {}
	reset = get_object_or_404(PasswordReset, key=key)
	form = SetPasswordForm(user=reset.user, data=request.POST or None)

	if form.is_valid():
		form.save()
		context['success'] = True

	context['form'] = form

	return render(request, template_name, context)

simplemooc/accounts/templates/accounts/dashboard.html
{% extends "base.html" %}

{% load courses_tags %}
{% load_my_courses user as enrollments %}

{% block content %}
	<div class="pure-g-r content-ribbon">
	    <div class="pure-u-1">
	        <ul class="breadcrumb">
	            {% block breadcrumb %}
	            <li><a href="{% url 'accounts:dashboard' %}">Meu Painel</a></li>
	            {% endblock %}
	        </ul>
	    </div>

	    <div class="pure-u-1-3">
	        <div class="pure-menu pure-menu-open">
	            <ul>
	            	<li class="pure-menu-heading"> Bem vindo, {{ user }}</li>
	            	{% block menu_options %}
		            	{% my_courses user %}
		                <li class="pure-menu-heading">Configurações de Conta</li>
						<li>
							<a href="{% url 'accounts:edit' %}">
								<i class="fa fa-cog"></i>
								Editar Conta
							</a>
						</li>
		                <li>
		                	<a href="{% url 'accounts:edit_password' %}">
		                		<i class="fa fa-lock"></i>
		                		Editar Senha
		                	</a>
		                </li>
	                {% endblock %}
	            </ul>
	        </div>
	    </div>
	    <div class="pure-u-2-3">
	        <div class="inner">
	        	{% block dashboard_content %}
	                <h2>Meus Cursos</h2>

	                {% for enrollment in enrollments %}
		                <div class="well">
		                    <h3>
		                    	{{ enrollment.course }} ({{ enrollment.course.start_date|date:'d/m/Y'|default:'Sem data' }})
		                    </h3>
		                    
		                    {{ enrollment.course.description|linebreaks }}

		                    <div class="pure-controls">
		                        <a href="{{ url 'courses:announcements' enrollment.course.slug }}" class="pure-button pure-button-primary">Acessar</a>
		                        <a href="#" class="pure-button button-error">Cancelar</a>
		                    </div>
		                </div>
	                {% empty %}
		                <aside class="pure-u-1">
		                    <p>Nenhum curso inscrito</p>
		                </aside>
	                {% endfor %}
	            {% endblock %}
	        </div>
	    </div>
	</div>
{% endblock %}

simplemooc/accounts/templates/accounts/edit.html
{% extends "accounts/dashboard.html" %}

{% block breadcomb %}
	{{ block.super }}
	<li>/</li>
	<li><a href="{% url 'accounts:edit' %}">Editar Conta</a></li>
{% endblock %}

{% block dashboard_content %}
	<form class="pure-form pure-form-stacked" method="post">
		{% csrf_token %}
        <fieldset>
    		{% for error in form.non_field_errors %}
    			{{ error }}
    		{% endfor %}

        	{% for field in form %}
	            <div class="pure-control-group">
	            	{{ field.label_tag }}
	            	{{ field }}
	            	{{ field.errors }}
	            </div>
            {% endfor %}
            <div class="pure-controls">
                <button type="submit" class="pure-button pure-button-primary">Salvar modificações</button>
            </div>
        </fieldset>
    </form>
{% endblock %}

simplemooc/accounts/templates/accounts/edit_password.html
{% extends "accounts/dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'accounts:edit_password' %}">Editar Senha</a></li>
{% endblock %}

{% block dashboard_content %}
    <form class="pure-form pure-form-stacked" method="post">
        {% csrf_token %}

        {% if success %}
            <p>A sua senha foi alterada com sucesso</p>
        {% endif %}
        
        <fieldset>
            {{ form.non_field_errors }}
            {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
            {% endfor %}

            <div class="pure-controls">
                <button type="submit" class="pure-button pure-button-primary">Alterar Senha</button>
            </div>
        </fieldset>
    </form>
{% endblock %}

simplemooc/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            <h2>Informe seus dados de cadastro</h2>
            <form class="pure-form pure-form-stacked" method="post">
                {% csrf_token %}
                <fieldset>
                    {{ form.non_field_errors }}

                    {% for field in form %}
                        <div class="pure-control-group">
                            {{ field.label_tag }}
                            {{ field }}
                            {{ field.errors }}
                        </div>
                    {% endfor %}

                    <div class="pure-controls">
                        <button type="submit" class="pure-button pure-button-primary">Entrar</button>
                    </div>
                </fieldset>
                <p>
                    Não é cadastrado? <a href="{% url 'accounts:register' %}" title="">Cadastre-se</a> <br />
                    Esqueceu a senha? <a href="{% url 'accounts:password_reset' %}" title="">Nova senha</a> <br />
                </p>
            </form>
        </div>
    </div>
{% endblock %}

simplemooc/accounts/templates/accounts/password_reset.html
{% extends "base.html" %}

{% block content %}
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
        	{% if success %}
        		<p> Um e-mail foi enviado para o e-mail informado com mais detalhes de como criar uma nova senha. </p>
        	{% else%}
	            <h2>Informe seu e-mail</h2>
	            <form class="pure-form pure-form-stacked" method="post">
	                {% csrf_token %}
	                <fieldset>
	                    {{ form.non_field_errors }}

	                    {% for field in form %}
	                        <div class="pure-control-group">
	                            {{ field.label_tag }}
	                            {{ field }}
	                            {{ field.errors }}
	                        </div>
	                    {% endfor %}

	                    <div class="pure-controls">
	                        <button type="submit" class="pure-button pure-button-primary">Enviar E-mail</button>
	                    </div>
	                </fieldset>
	            </form>
        	{% endif %}
        </div>
    </div>
{% endblock %}

simplemooc/accounts/templates/accounts/password_reset_confirm.html
{% extends "base.html" %}

{% block content %}
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
        	{% if success %}
        		<p> Sua senha foi criada com sucesso! </p>
        	{% else%}
	            <h2>Informe sua nova senha</h2>
	            <form class="pure-form pure-form-stacked" method="post">
	                {% csrf_token %}
	                <fieldset>
	                    {{ form.non_field_errors }}

	                    {% for field in form %}
	                        <div class="pure-control-group">
	                            {{ field.label_tag }}
	                            {{ field }}
	                            {{ field.errors }}
	                        </div>
	                    {% endfor %}

	                    <div class="pure-controls">
	                        <button type="submit" class="pure-button pure-button-primary">Alterar senha</button>
	                    </div>
	                </fieldset>
	            </form>
        	{% endif %}
        </div>
    </div>
{% endblock %}

simplemooc/accounts/templates/accounts/password_reset_mail.html
<p> 
	Para criar uma nova senha acesse o seguinte link: 
	<a href="{% url 'accounts:password_reset_confirm' key=reset.key %}" title="Link para nova senha"> 
		Criar nova senha
	</a>
</p>

simplemooc/accounts/templates/accounts/register.html
{% extends "base.html" %}

{% block content %}
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            <h2>Informe seus dados</h2>
            <form class="pure-form pure-form-stacked" method="post">
                {% csrf_token %}
                <fieldset>
                    {{ form.non_field_errors }}

                    {% for field in form %}
                        <div class="pure-control-group">
                            {{ field.label_tag }}
                            {{ field }}
                            {{ field.errors }}
                        </div>
                    {% endfor %}

                    <div class="pure-controls">
                        <button type="submit" class="pure-button pure-button-primary">Cadastrar</button>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
{% endblock %}